import Sidebar from "@/layout/Sidebar";
import Navbar from "../layout/Navbar";
import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.css"
        />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick-theme.min.css"
        />
      </head>
      <body className="flex flex-col h-screen overflow-auto">
        <Navbar />
        <div className="flex-1 relative bg-[#dfe2e8]">
          <Sidebar />
          <div className="ml-[15%] bg-[#e7e9e7] h-full">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
